# Generated by Django 5.0.4 on 2024-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id de usuario')),
                ('username', models.CharField(max_length=52, verbose_name='Nombre de usuario')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Amigos desde')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id de usuario')),
                ('username', models.CharField(max_length=52, verbose_name='Nombre de usuario')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Enviado el')),
            ],
        ),
    ]
