# Generated by Django 5.0.4 on 2024-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsrequest',
            name='id_requested',
            field=models.IntegerField(null=True, verbose_name='A quien'),
        ),
    ]
