# Generated by Django 5.0.4 on 2024-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_friendsrequest_id_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='belongs_to',
            field=models.CharField(max_length=52, null=True, verbose_name='Pertenece a'),
        ),
    ]
