# Generated by Django 5.0.4 on 2024-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contacts_belongs_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, verbose_name='Remitente')),
                ('receiver', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('issue', models.CharField(max_length=150, verbose_name='Asunto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
            ],
        ),
    ]
