# Generated by Django 5.0.4 on 2024-04-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='ListMessages',
        ),
    ]
