# Generated by Django 5.0.4 on 2024-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_messages_listmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsrequest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at_2',
            field=models.DateField(auto_now=True, verbose_name='Amigos desde'),
        ),
    ]
